export const SPRAY_PRODUCT_OPTIONS = [
  'LI 700',
  'GLYPHOSATE',
  'DESICA',
  'INTERLOCK',
  'MANIPULATOR',
  'RAXIL',
  '2-4,D',
  'AATREX',
  'ALLEGRO',
  'AXIAL EXTREME',
  'BASAGRAN FORTE',
  'BRAVO',
  'EDGE',
  'Envita',
  'EPTAM',
  'GLUFOSINATE',
  'Centurioun',
  'HEAT',
  'HI ACTIVATE',
  'HINGE',
  'IMPACT',
  'KOMODO',
  'MANZATE MAX',
  'MIAVIS DUO',
  'MINECTO',
  'MOVENTO',
  'MSO',
  'ON-DECK',
  'ORANDIS',
  'FORCE FIGHTER',
  'PROLINE GOLD',
  'PROLINE/GOLD',
  'PROSARO/PRO',
  'PYTHON',
  'QUAD TOP',
  'REFLEX',
  'Roundup WeatherMax',
  'Round up Extend',
  'Liberty 280',
  'Glyphosate 4L',
  '2,4-D Amine',
  'Atrazine 500',
  'Dicamba',
  'Metribuzin 75DF',
  'Assure II',
  'Select 1EC',
  'Tebuconazole',
  'TRICOR',
  'UPTAKE',
  'RT-540',
  'Outshine',
  'Viper ADV',
  'Liberty',
  'Masterlock',
  'Dual Magnum',
  'Buctril M',
  'Laudis',
  'Pardner',
];